# config/agent_config.yaml

PROCESS_MODEL:
  model_platform: "SILICONFLOW"
  model_type: "Qwen/Qwen2.5-14B-Instruct"
  url: "https://api.siliconflow.cn/v1/chat/completions"
  model_config:
    temperature: 1.2
    max_tokens: 4096
    stream: False
  model_context: 16000

GENERATE_MODEL:
  model_platform: "SILICONFLOW"
  model_type: "Qwen/Qwen3-30B-A3B"
  url: "https://api.siliconflow.cn/v1/chat/completions"
  model_config:
    temperature: 0.5
    max_tokens: 4096
    stream: True
  model_context: 16000